---
name: abstractgames
version: "20.2.4"
summary: "The Ultimate Suite of Strategy, Abstract, and Arcade Games"
description: "This is a collection of strategy and arcade games which are simple, light, interesting, and modern."
grade: stable
confinement: strict
base: core18
architectures:
  - amd64

apps:
    chess:
        command: kf5-launch $SNAP/usr/bin/chess
        common-id: org.gitlab.abstractgames.chess.desktop
        desktop: usr/share/applications/abstractgames/chess.desktop
        plugs:
                #- browser-support
            - desktop
            - desktop-legacy
              #- home
              # - kde-frameworks-5-plug ???
              #- pulseaudio
              #- network
            - opengl
            - unity7
            - x11
            - wayland

    mines:
        command: kf5-launch $SNAP/usr/bin/mines
        common-id: org.gitlab.abstractgames.mines.desktop
        desktop: usr/share/applications/abstractgames/mines.desktop
        plugs:
                #- browser-support
            - desktop
            - desktop-legacy
              #- home
              # - kde-frameworks-5-plug ???
              #- pulseaudio
              #- network
            - opengl
            - unity7
            - x11
            - wayland

    tictactoe:
        command: kf5-launch $SNAP/usr/bin/tictactoe
        common-id: org.gitlab.abstractgames.tictactoe.desktop
        desktop: usr/share/applications/abstractgames/tictactoe.desktop
        plugs:
                #- browser-support
            - desktop
            - desktop-legacy
              #- home
              # - kde-frameworks-5-plug ???
              #- pulseaudio
              #- network
            - opengl
            - unity7
            - x11
            - wayland
    samegame:
        command: kf5-launch $SNAP/usr/bin/samegame
        common-id: org.gitlab.abstractgames.samegame.desktop
        desktop: usr/share/applications/abstractgames/samegame.desktop
        plugs:
                #- browser-support
            - desktop
            - desktop-legacy
              #- home
              # - kde-frameworks-5-plug ???
              #- pulseaudio
              #- network
            - opengl
            - unity7
            - x11
            - wayland
    jetfighter:
        command: kf5-launch $SNAP/usr/bin/jetfighter
        common-id: org.gitlab.abstractgames.jetfighter.desktop
        desktop: usr/share/applications/abstractgames/jetfighter.desktop
        plugs:
                #- browser-support
            - desktop
            - desktop-legacy
              #- home
              # - kde-frameworks-5-plug ???
              #- pulseaudio
              #- network
            - opengl
            - unity7
            - x11
            - wayland
    bots:
        command: kf5-launch $SNAP/usr/bin/bots
        common-id: org.gitlab.abstractgames.bots.desktop
        desktop: usr/share/applications/abstractgames/bots.desktop
        plugs:
                #- browser-support
            - desktop
            - desktop-legacy
              #- home
              # - kde-frameworks-5-plug ???
              #- pulseaudio
              #- network
            - opengl
            - unity7
            - x11
            - wayland
    igo:
        command: kf5-launch $SNAP/usr/bin/igo
        common-id: org.gitlab.abstractgames.igo.desktop
        desktop: usr/share/applications/abstractgames/igo.desktop
        plugs:
                #- browser-support
            - desktop
            - desktop-legacy
              #- home
              # - kde-frameworks-5-plug ???
              #- pulseaudio
              #- network
            - opengl
            - unity7
            - x11
            - wayland

plugs:
    kde-frameworks-5-plug:
        interface: content
        content: kde-frameworks-5-core18-all 
        default-provider: kde-frameworks-5-core18
        target: kf5

parts:
    abstractgamesbuild:
        plugin: cmake
        source-type: git
        source: https://gitlab.com/abstractsoftware/abstract-games.git
        source-commit: "29f29a1914f552fe85b17bdeb404dae960b6218a"

        build-packages: 
            - build-essential
            - libegl1-mesa-dev
              #- sonnet-plugins

        build-snaps: 
            - kde-frameworks-5-core18-sdk

        configflags:
            - "-DCMAKE_INSTALL_PREFIX=/usr/bin"
            - "-DPLUGIN_INSTALL_DIR=/usr/lib"

        override-pull: |
            snapcraftctl pull
            sed -i.bak -e 's|Icon=chess|Icon=/usr/share/icons/hicolor/scalable/apps/chess.svg|g' resource/chess/chess.desktop
            sed -i.bak -e 's|Icon=mines|Icon=/usr/share/icons/hicolor/scalable/apps/mines.svg|g' resource/mines/mines.desktop
            sed -i.bak -e 's|Icon=tictactoe|Icon=/usr/share/icons/hicolor/scalable/apps/tictactoe.svg|g' resource/tictactoe/tictactoe.desktop
            sed -i.bak -e 's|Icon=samegame|Icon=/usr/share/icons/hicolor/scalable/apps/samegame.svg|g' resource/samegame/samegame.desktop
            sed -i.bak -e 's|Icon=jetfighter|Icon=/usr/share/icons/hicolor/scalable/apps/jetfighter.svg|g' resource/jetfighter/jetfighter.desktop
            sed -i.bak -e 's|Icon=bots|Icon=/usr/share/icons/hicolor/scalable/apps/bots.svg|g' resource/bots/bots.desktop
            sed -i.bak -e 's|Icon=igo|Icon=/usr/share/icons/hicolor/scalable/apps/igo.svg|g' resource/igo/igo.desktop

    kde-frameworks-5-env:
        plugin: dump
        source: https://github.com/apachelogger/kf5-snap-env.git
